export const STATES = [
  { label: "Alabama", string: "AL" },
  { label: "Alaska", string: "AK" },
  { label: "American Samoa", string: "AS" },
  { label: "Arizona", string: "AZ" },
  { label: "Arkansas", string: "AR" },
  { label: "California", string: "CA" },
  { label: "Colorado", string: "CO" },
  { label: "Connecticut", string: "CT" },
  { label: "Delaware", string: "DE" },
  { label: "District of Columbia", string: "DC" },
  { label: "Florida", string: "FL" },
  { label: "Georgia", string: "GA" },
  { label: "Guam", string: "GU" },
  { label: "Hawaii", string: "HI" },
  { label: "Idaho", string: "ID" },
  { label: "Illinois", string: "IL" },
  { label: "Indiana", string: "IN" },
  { label: "Iowa", string: "IA" },
  { label: "Kansas", string: "KS" },
  { label: "Kentucky", string: "KY" },
  { label: "Louisiana", string: "LA" },
  { label: "Maine", string: "ME" },
  { label: "Maryland", string: "MD" },
  { label: "Massachusetts", string: "MA" },
  { label: "Michigan", string: "MI" },
  { label: "Minnesota", string: "MN" },
  { label: "Mississippi", string: "MS" },
  { label: "Missouri", string: "MO" },
  { label: "Montana", string: "MT" },
  { label: "Nebraska", string: "NE" },
  { label: "Nevada", string: "NV" },
  { label: "New Hampshire", string: "NH" },
  { label: "New Jersey", string: "NJ" },
  { label: "New Mexico", string: "NM" },
  { label: "New York", string: "NY" },
  { label: "North Carolina", string: "NC" },
  { label: "North Dakota", string: "ND" },
  { label: "Northern Mariana Islands", string: "MP" },
  { label: "Ohio", string: "OH" },
  { label: "Oklahoma", string: "OK" },
  { label: "Oregon", string: "OR" },
  { label: "Pennsylvania", string: "PA" },
  { label: "Puerto Rico", string: "PR" },
  { label: "Rhode Island", string: "RI" },
  { label: "South Carolina", string: "SC" },
  { label: "South Dakota", string: "SD" },
  { label: "Tennessee", string: "TN" },
  { label: "Texas", string: "TX" },
  { label: "Utah", string: "UT" },
  { label: "Vermont", string: "VT" },
  { label: "Virginia", string: "VA" },
  { label: "U.S. Virgin Islands", string: "VI" },
  { label: "Washington", string: "WA" },
  { label: "West Virginia", string: "WV" },
  { label: "Wisconsin", string: "WI" },
  { label: "Wyoming", string: "WY" },
];
